### ISSUE TITLE
Not can open game

### ISSUE THREAD

**Issue by Anton34123** [f-rosato/battlematica#2]
python3 run_game.py -f 3v1_square.json -t 1200 -d
Python

**Comment by f-rosato** [comment]
Can you drop a bit more info about the error you are experiencing?

**Comment by Anton34123** [comment]
where is the "arcade" module located?

**Comment by f-rosato** [comment]
It's an optional requirement. In fact it's listed in optional-requirements.txt. You must install it from pypi

**Comment by f-rosato** [comment]
I will close this issue in a short while if there is no further update.

**Comment by f-rosato** [comment]
Updated README.md in commit  https://github.com/f-rosato/battlematica/commit/a70805c63fc61ad830aa92ddf0d7e7d67146b912 clarifying that a proper environment w/ requirements must be set up to run the game with the suggested command.
